hal_services: Newer EABIs require explicit .arch_extension sec
Eliminates assembler messages such as:
Error: selected processor does not support ARM mode `smc #0'